### ISSUE TITLE
com.miui.gallery -> KAUNISTO

### ISSUE THREAD

**Issue by Vihru** [dogiex/MA-XML-9.0-FINNISH#10]
## Perustiedot
Laite: Mi6 (sagit)
MIUI versio: Weekly 7.8.17

## Kuvaus
Galleriassa kun muokkaa kuvaa niin lukee "KAUNISTO"

## Kuvakaappaus
![screenshot_2017-08-20-08-32-49-753_com miui gallery](https://user-images.githubusercontent.com/16348370/29492387-a9caae6e-8582-11e7-98cf-611b94073a48.png)

**Comment by dogiex** [comment]
Ohhoh, kuinkas se nyt tuollalailla. 😂
