### ISSUE TITLE
com.duokan.phone.remotecontroller -> paritettu

### ISSUE THREAD

**Issue by Vihru** [dogiex/MA-XML-9.0-FINNISH#16]
## Perustiedot
Laite: Mi6 (sagit)
MIUI versio: Weekly 7.9.7

## Kuvaus
onko tuo paritettu teksti täysin oikein.. koska siis sitä pitää painaa jotta se tallentaa tuon kaukosäätimen, jos ei sitä "paritettu" tekstiä paina niin kaukosäädin ei tallennu.

## Kuvakaappaus

![screenshot_2017-09-09-11-12-21-862_com duokan phone remotecontroller](https://user-images.githubusercontent.com/16348370/30238666-ca9619d6-9553-11e7-82ab-2c2fe894c19b.png)

**Comment by dogiex** [comment]
Nähtävästi virhe käännöksessä. Käännetään se "Tallenna" painikkeeksi.

**Comment by dogiex** [comment]
Ilmeisesti enkuksi se on "Paired", joten käännös on silloin aivan oikein.

**Comment by Vihru** [comment]
Ei silti kyllä millään tavalla järkevä :D

**Comment by dogiex** [comment]
Se on totta. Muutetaanko se "Tallenna" käännökseksi?

**Comment by Vihru** [comment]
Olisi paljon fiksumpi niin, koska siitä napista se vasta sen tallentaa.
