### ISSUE TITLE
com.miui.home -> päiväys

### ISSUE THREAD

**Issue by Vihru** [dogiex/MA-XML-9.0-FINNISH#18]
## Perustiedot
Laite: mi6 sagit
MIUI versio: Weekly 7.11.2

## Kuvaus
tuo päivämäärä ikäänku kahteen kertaan, pitäskö jotenki muuttaa järkevämmäks?
ensin lukee 3 marraskuu ja alempana perj. 2017.11.3. 

## Kuvakaappaus
![screenshot_2017-11-03-11-04-54-007_com miui home](https://user-images.githubusercontent.com/16348370/32366641-9aeda7e4-c087-11e7-9ea9-20926baa2234.png)

## Lokitieto
Liitä tähän logcat lokitieto, mikäli on Bugi ja saat otettua sellaisen

**Comment by dogiex** [comment]
Joo voisin katsoa tuota viikonloppuna
