### ISSUE TITLE
Updater-sovellus englanniksi

### ISSUE THREAD

**Issue by Vihru** [dogiex/MA-XML-9.0-FINNISH#2]
## Perustiedot
Laite: Mi6 (sagit)
MIUI versio: Weekly 7.8.10 REUPLOADED

## Kuvaus
Käännös puuttuu updater-sovelluksesta.  updater-sovellus varmaan ota-päivityksien takia muuttunut. nimi ilmeisesti nykyään joku pl.zdunex25.updater?
PS. mistä tuon labelin saa valittua...  

## Kuvakaappaus
![screenshot_2017-08-12-15-41-36-318_pl zdunex25 updater](https://user-images.githubusercontent.com/16348370/29240829-8da37c4c-7f75-11e7-9027-bd4c8b9616ca.png)

**Comment by dogiex** [comment]
Labels painikkeesta  
[Kuva](https://a.uguu.se/o0iEi72IUuby_chrome_2017-08-12_16-52-26.png)

Vai onko teillä edes tuota? Voinko vain minä sen laittaa? Tuli vaan mieleen. :)

**Comment by Vihru** [comment]
mä en kyllä löydä tapaa mistä sen vois määrittää.. 
![labels](https://user-images.githubusercontent.com/16348370/29241330-0f1e93ec-7f80-11e7-822f-3f4048125235.png)

**Comment by Vihru** [comment]
hei, tarkistin tän myös toisella kielellä.. ongelma ei ole pelkästään suomenkielen käännöksessä..

**Comment by dogiex** [comment]
Eli nähtävästi tuo Labels on vain projektin ylläpitäjien hallinnassa, jos en anna oikeutta jollekin toiselle myös. Nyt olen taas astetta fiksumpi. :)
Joo toi päivittäjän käännökset pitäisi olla myös käännetty, tosin ei kerinnyt vielä starttiin mukaan vaan julkaisun jälkeen sain ne käännettyä, jos en väärin muista. ;)

**Comment by dogiex** [comment]
Minkäslainen tuon Päivittäjäsovelluksen menuvalikko on nykyään? :)

**Comment by Vihru** [comment]
Hei, tämmönen..

la 12. elokuuta 2017 klo 18.17 Dogiex <notifications@github.com> kirjoitti:

**Comment by Vihru** [comment]
![screenshot_2017-08-12-18-23-06-539_pl zdunex25 updater](https://user-images.githubusercontent.com/16348370/29241896-915a90a8-7f8b-11e7-8170-108ee76f3547.png)

**Comment by dogiex** [comment]
Katsotaan seuraavassa weeklyssä uudelleen josko olisi suomeksi. Käännetty nuo on kyllä, joten ei varmaan kerinnyt mukaan.

**Comment by Vihru** [comment]
juu, se ei ollut muillakaan kielillä kääntyny.. joten ei sun käännöksistä ole ainakaan kiinni..

**Comment by Vihru** [comment]
tämä on nyt kunnossa.. 
![screenshot_2017-08-18-12-28-57-775_pl zdunex25 updater](https://user-images.githubusercontent.com/16348370/29452999-dabd67aa-8410-11e7-8266-6625fa8713b5.png)
