### ISSUE TITLE
com.miui.securitycenter -> keyword blocklist ja exceptions

### ISSUE THREAD

**Issue by Vihru** [dogiex/MA-XML-9.0-FINNISH#26]
## Perustiedot
Laite: Mi Note 3 (jason)
MIUI versio: Weekly 8.2.1

## Kuvaus
com.miui.securitycenter ja  keyword blocklist ja exceptions

## Kuvakaappaus
![screenshot_2018-02-20-09-43-48-643_com miui securitycenter](https://user-images.githubusercontent.com/16348370/36418209-dd6c9738-1636-11e8-8301-c3a487944645.png)

**Comment by Vihru** [comment]
Hei, ilmeisesti sinulla muita hommia enemmän.. ?

**Comment by dogiex** [comment]
Tällä hetkellä on juu ollut aika kiireistä muissa projekteissa ja taas kuukauden päästä on järjestettävä verkkopelitapahtuma, jossa olen pääjärjestäjän roolissa, joten aikaa vievää hommaa sekin.
Hieman on tauolle jäänyt tämä käännösprojekti, mutta yritän ainakin nämä issuet saada tehtyä/korjattua.

**Comment by Vihru** [comment]
juu, kyllähän mäkin osaisin jotain kääntää.. se olis yks myös että yrittäsin pahimpia puutteita kääntää jos et ehdi, muuten joutuu vaihtaa xiaomit pois jos menee suomi ihan piloille.

**Comment by dogiex** [comment]
Hehe, ei se piloille mene. On vaan tällä hetkellä ollut niin isot päivitykset, kun Android Oreo tuli niin mun täytyy nekin muutokset tehdä tuonne. Se kestää aikansa. Heti kun olen päässyt sen kynnyksen yli eli ne kaikki tehtyä niin nuo pienet käännöspäivitykset menevät nopeasti.

**Comment by Vihru** [comment]
joo no hieno kuulla! sais olla enemmän niitä ihmisiä ketkä arvostais sun tekemää käännöstyötä ja lahjottais vaikka vähän.. tuntuu että olen ainoa.

**Comment by dogiex** [comment]
Joo aikaa vievää hommaahan tämä on. Varsinkin jos Android versio muuttuu niin kaikki nekin pitää itse sinne käsin muuttaa.
On tuossa projektin alkuvaiheilla yksi lahjoittanut hieman kahvirahaa, mutta siihen se nyt on jäänytkin.
Uskon, että kyllä Xiaomi.eu rommin käyttäjät arvostavat käännöstyötäni, ei ainakaan valituksia ole kuulunut. :D

**Comment by Vihru** [comment]
hyvä, laitoin taas sulle vähän kahvi/kaljarahaa ku siitä pitkä aika ku
viimeks rahallisesti sua kiittäny!

su 4. maaliskuuta 2018 klo 10.26 Dogiex <notifications@github.com>
kirjoitti:

**Comment by dogiex** [comment]
Hehe kiitos paljon!
