### ISSUE TITLE
com.android.settings -> wifi

### ISSUE THREAD

**Issue by Vihru** [dogiex/MA-XML-9.0-FINNISH#3]
## Perustiedot
Laite: Mi6 (sagit)
MIUI versio: Weekly 7.8.10 REUPLOADED

## Kuvaus
Wifi-asetuksissa kohta yhdistämisen tila -> high mode  sekä comtible mode (kirjotusvirhe tuossa myös)
sekä älykäs tiedonsiirtostrategia kohdassa normaali-tila, extreme-tila ja sulje? tuohon sulje kohtaan voisi laittaa myös jotain että pois käytöstä tms?

## Kuvakaappaus
![screenshot_2017-08-12-15-42-08-895_com android settings](https://user-images.githubusercontent.com/16348370/29240873-3b9b0fc2-7f76-11e7-9ae8-901247c26238.png)

**Comment by dogiex** [comment]
Mitä se "sulje" vaihtoehto siis tekee tuossa "Älykäs tiedonsiirtostrategian" valikossa?
Englanniksi se on käännetty "close".

**Comment by dogiex** [comment]
Yhdistämisen tila valikon käänsin nyt näin:
- Yhteensopiva tila
- Korkea tila

Älykäs tiedonsiirtostrategian valikko:
- Sulje
- Normaali tila
- Äärimmäinen tila

**Comment by Vihru** [comment]
Sen saa vaan valita onko se sulje,normaali vai äärimmäinen, siitä en tiedä mitä se oikeasti tekee.. mutta tuokin on nyt parempi joka tapauksessa.. hienoa!

**Comment by dogiex** [comment]
Jätetään se vielä Sulje käännökseksi, katsotaan josko enkuksi muuttavat sen, tosin samaa saatiin odottaa myös tuossa toisessa valikossa ja mitään ei ole vielä tapahtunut sen osalta. :)

**Comment by Vihru** [comment]
juu toi on hyvä tuollain.. jos ei tule sitten enkuksi mitään muutoksia..
