### ISSUE TITLE
Personalised Ad recommendation

### ISSUE THREAD

**Issue by Vihru** [dogiex/MA-XML-9.0-FINNISH#33]
## Perustiedot
Laite: Mi Note 3 (jason)
MIUI versio: Weekly 8.3.8

## Kuvaus
kun puhelinta ihan alussa asentaa tulee tuollainen enkuksi.

## Kuvakaappaus

![screenshot_2018-03-09-06-28-34-832_com android provision](https://user-images.githubusercontent.com/16348370/37206327-dc6c9654-23a0-11e8-807e-652176bbcc90.png)

**Comment by Vihru** [comment]
onnistuuko? :p

**Comment by dogiex** [comment]
@Vihru tänään taas löytyy aikaa hieman käännellä, loppupäivästä tulee kyläläisiä ja pitää vaihtaa näyttö Mi Max 2 luuriin 😉
