### ISSUE TITLE
com.android.quicksearchbox -> favorites

### ISSUE THREAD

**Issue by Vihru** [dogiex/MA-XML-9.0-FINNISH#4]
## Perustiedot
Laite: Mi6 (sagit)
MIUI versio: Weekly 7.8.10 REUPLOADED

## Kuvaus
Asetukset -> järjestelmäsovellukset -> haku
haettavat kohteet listan alla kohta favorites, titles in favorites..

## Kuvakaappaus
![screenshot_2017-08-12-15-53-59-067_com android quicksearchbox](https://user-images.githubusercontent.com/16348370/29240888-b51ff920-7f76-11e7-890c-328f3848ac8c.png)

**Comment by dogiex** [comment]
Tähän ei vielä ainakaan ollut käännöspohjaa tiedostoissa olemassa. Jos aktivoit tuon Favorites päälle niin mitäköhän sillä voi hakea?

**Comment by Vihru** [comment]
Hei, ei kyllä mitään hajua.  Puhelin on latauksessa ni en tänää enää
kokeile..  kokeilen huomenna.  jls selviäis..

la 12. elokuuta 2017 klo 20.00 Dogiex <notifications@github.com> kirjoitti:

**Comment by Vihru** [comment]
liittyy ilmeisesti johki quickcardiin ja tulee kiinaa kun avaan ABOUT favorites kohdan hakukentästä...

**Comment by dogiex** [comment]
Aa. Eli varmaan poistuu käytöstä weeklyjen myötä, koska sitä ominaisuutta tuskin tullaan näkemään EU rommissa.

**Comment by Vihru** [comment]
nii, ei sieltä haku sovelluksesta oo google drivekää poistunu vaikka ei se haku niistä tiedostoista toimi..

**Comment by dogiex** [comment]
Joo toi google drive haku olisi kiva saada toimintaa, olisi kätevä kyllä. Mikäköhän siinä mahtaa olla? Onko se joskus toiminut oikein? En ole itse sitä ikinä ennen käyttänyt, mutta nytten kyllä tulisi käyttöä. :)

**Comment by Vihru** [comment]
Ei oo mulla ainakaan koskaan toiminu.. sanonu ingbryzlle monta kertaa mut
tuntuu ettei ota kuuleviin korviin..

**Comment by Vihru** [comment]
![screenshot_2017-08-28-23-07-51-862_com android quicksearchbox](https://user-images.githubusercontent.com/16348370/29791511-daebfa6a-8c45-11e7-9029-836ab0777248.png)
tää issue on tainnu korjaantua?

**Comment by dogiex** [comment]
Jos se ei enää näy niin silloin on korjaantunut, kiinasälää... Kiitos ilmoituksesta.
