### ISSUE TITLE
com.duokan.phone.remotecontroller kokonaan englanniksi

### ISSUE THREAD

**Issue by Vihru** [dogiex/MA-XML-9.0-FINNISH#5]
## Perustiedot
Laite: Mi6 (sagit)
MIUI versio: Weekly 7.8.10 REUPLOADED

## Kuvaus
Kaukosäädin sovellus kokonaan englanniksi.. tämä ongelma oli myös jo aikaisemmin niinku tiedätkin..

## Kuvakaappaus
![screenshot_2017-08-12-19-09-01-032_com duokan phone remotecontroller](https://user-images.githubusercontent.com/16348370/29242241-05bc7cc6-7f92-11e7-8fd5-866bb88ab61c.png)

**Comment by dogiex** [comment]
Dear @ingbrzy Mi Remote app is still in English. Do you have any idea how we can apply the Finnish translations for it?
The .apk is translated.

**Comment by ingbrzy** [comment]
translate it on Crowdin https://crowdin.com/project/mi-apps/fi#

**Comment by dogiex** [comment]
Thank you. I have applied to be a translator long ago, hope they will accept me soon. :)

**Comment by dogiex** [comment]
@Vihru pääsen siis kääntämään tätä heti, kun hyväksyvät minut tuohon Xiaomin viralliseen Mi Apps kääntäjäryhmään. Käyttiksen osalta heillä meni lähes vuosi, kauankohan tässä menee.. Tai on mennyt jo pari kuukautta eikä mitään ole vielä kuulunut, mutta varmaan joku vuosi sitten. :)

**Comment by dogiex** [comment]
@ingbrzy So I can forget the [XML Compare](https://github.com/ingbrzy/Xiaomi.eu-MIUIv9-XML-Compare) of Mi Remote (XMRemoteController.apk) if it isn't used?

**Comment by Vihru** [comment]
@dogiex toivotaan että hyväksyvät pian...

**Comment by ingbrzy** [comment]
Fixed for 7.9.7...

**Comment by dogiex** [comment]
Thank you @ingbrzy !
