### ISSUE TITLE
com.android.contacts -> null

### ISSUE THREAD

**Issue by Vihru** [dogiex/MA-XML-9.0-FINNISH#6]
## Perustiedot
Laite: Mi6 (sagit)
MIUI versio: Weekly 7.8.10 REUPLOADED

## Kuvaus
jos saat puhelun tuntemattomasta numerosta, sen alapuolella lukee null? 

## Kuvakaappaus
![screenshot_2017-08-15-16-09-00-947_com android contacts](https://user-images.githubusercontent.com/16348370/29317369-46271fc0-81d4-11e7-9d02-02c23e7f70a6.png)

**Comment by dogiex** [comment]
Nullin tilalla pitäisi olla joko ei mitään, eli kellonaika siirretty sen tilalle, numero mistä soitettu tai paikkakunta. Taitaa poistua itsestään weeklyjen myötä. Seurataan tilannetta.

**Comment by dogiex** [comment]
Osaatko sano, onko tämä ongelma vielä olemassa 7.8.17 versiossa?

**Comment by Vihru** [comment]
Hei, testasin nii on kyllä..

**Comment by dogiex** [comment]
Tuleeko se myös esiin enkun kielellä?

**Comment by Vihru** [comment]
joo, lukee myös null enkunkielellä.

**Comment by dogiex** [comment]
Eli tämä ei ole suomi-käännöksestä kiinni, pitäisi poistua ajan myötä, kun huomaavat bugin tai kerro bugista xiaomi.eu foorumilla.

**Comment by Vihru** [comment]
uusin weekly 7.8.31 ja mi max 2, ongelma on ilmeisesti poistunu ku ingbrzyä tästä aiheesta pommitin. 
![screenshot_2017-09-01-06-37-27-617_com android contacts](https://user-images.githubusercontent.com/16348370/29954408-4200368e-8ee0-11e7-9e55-87789d67f229.png)

**Comment by dogiex** [comment]
Hienoa! Suljen tämän siis.
