### ISSUE TITLE
com.miui.home.png -> kello-widgetti

### ISSUE THREAD

**Issue by Vihru** [dogiex/MA-XML-9.0-FINNISH#7]
## Perustiedot
Laite: Mi6 (sagit)
MIUI versio: Weekly 7.8.17

## Kuvaus
Widgetti työpöydällä näyttää pvän vieläkin lyhennettynä ja sää myös englanniksi

## Kuvakaappaus
![screenshot_2017-08-18-12-20-49-088_com miui home](https://user-images.githubusercontent.com/16348370/29453099-23a42ac6-8411-11e7-9f1c-c877c5ebf401.png)

**Comment by dogiex** [comment]
Minun osaltani tämä on tehty. Päivittyy rommiin heti, kun päivittävät widgettiosiot rommista.

**Comment by Vihru** [comment]
nojuu, ärsyttävää kyllä että ei silti näy. voit sulkea.

**Comment by dogiex** [comment]
Suljetaan sitten, kun se on varmistettu. ;)

**Comment by Vihru** [comment]
laitoin ingbryzlle viestiä että käännökset ei kaikki näy vielä uusimmassa weeklyssä. että en tee sulle turhaan issueita.. :)

**Comment by Vihru** [comment]
ingbrzy vastas että sun käännökset ei oo ehtiny tarpeeks ajoissa..
"dead line is Thursday morning GMT.."  mutta eikai kyse ny ole tosta?

**Comment by dogiex** [comment]
Ens viikkoon siis 😉

**Comment by Vihru** [comment]
Toivotaan että kyse vaan tuosta..

**Comment by dogiex** [comment]
Käänsin tuon kyllä ennen torstaita, mutta katsotaan seuraavassa weeklyssä, mikä on tilanne. :)

**Comment by Vihru** [comment]
juu, en vaan usko että korjaantuu sillonkaan.. koska korjasit tämän monta päivää ennen torstaita.

**Comment by dogiex** [comment]
Katsoin käännöksien muutoslokia niin nyt päivittivät nuo widgettien käännökset, joten viimeistään ensi weeklyyn tulee kyllä muutos. :)

**Comment by Vihru** [comment]
juu näköjään kun katsoin kanssa ^^ vielä ku Mi Mover toimis...

**Comment by dogiex** [comment]
Ootko kokeillut sen myös enkulla?

**Comment by Vihru** [comment]
jaa sen toimivuuden? ikäänku sanoo että siirtää tiedostoja mutta esim
whatsapp ei datoinee siirry kuitenkaa

**Comment by dogiex** [comment]
Ilmeisesti en kääntänytkään tuota jo ennakkoon, nyt se tuli siis vasta käännettyä, eli pitäisi kyllä ens weeklyssä näkyä. Sori moka. :)

**Comment by Vihru** [comment]
Kyllä sä käänsit mutta ingbrzy ei ollu sitä stringsiä laittanu vielä sinne
sen paikkaan?

**Comment by ingbrzy** [comment]
fixed by https://github.com/dogiex/MA-XML-9.0-FINNISH/commit/1a90893adcff0ec445e7b24a4358f37a481ba735
