### ISSUE TITLE
com.android.settings.png -> Turn on find device

### ISSUE THREAD

**Issue by Vihru** [dogiex/MA-XML-9.0-FINNISH#8]
## Perustiedot
Laite: Mi6 (sagit)
MIUI versio: Weekly 7.8.17

## Kuvaus
ylhäällä ilmoitus englanniksi turn on find device

## Kuvakaappaus
![screenshot_2017-08-17-23-27-03-532_com android settings](https://user-images.githubusercontent.com/16348370/29453160-4eef16d2-8411-11e7-85cc-ed3bf5e7c51f.png)

**Comment by dogiex** [comment]
Tämä on käännetty.

**Comment by Vihru** [comment]
joo, no sitten jossain muualla vikaa..
