### ISSUE TITLE
com.android.settings --> laitteeni

### ISSUE THREAD

**Issue by Vihru** [dogiex/MA-XML-9.0-FINNISH#9]
## Perustiedot
Laite: Mi6 (sagit)
MIUI versio: Weekly 7.8.17

## Kuvaus
En tiedä saako nuo laitteeni tiedot myös suomeksi? missä näkyy siis battery, resolution jne.
![screenshot_2017-08-18-12-39-29-235_com android settings](https://user-images.githubusercontent.com/16348370/29453478-82f03f3c-8412-11e7-9c37-f4a865a7ea46.png)

**Comment by dogiex** [comment]
Kyllä ne saa käännettyä, ja se on tehty. :)
